# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  global_variable: 'Global value'
  
pool:
  vmImage: ubuntu-latest

jobs:
  - job:
    variables:
      global_variable: 'Local value'
    steps:
    - bash: |
        echo $(global_variable)
      displayName: 'Run a one-line script'
